# Generated by Django 2.2.4 on 2019-09-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('price', models.TextField()),
                ('title', models.TextField(default='this is nirajan ')),
            ],
        ),
    ]
